import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
const evidenceDir = new URL('../../../_scratch/evidence/', import.meta.url);
await mkdir(evidenceDir, { recursive: true });
const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 960 } });
const logs = [], requests = [], responses = [], pageErrors = [];
page.on('console', m => logs.push(m.text()));
page.on('pageerror', e => pageErrors.push(e.message));
page.on('request', req => { if (req.url().endsWith('/mcp') && req.postData()) requests.push(JSON.parse(req.postData())); });
page.on('response', async res => { if (res.url().endsWith('/mcp') && res.headers()['content-type']?.includes('application/json')) responses.push(await res.json()); });
await page.addInitScript(() => { window.__wire = []; window.addEventListener('message', e => { if (e.data?.jsonrpc) window.__wire.push(e.data); }); });
let corruptEvidence = false;
await page.route('**/mcp', async route => {
  const body = route.request().postDataJSON();
  if (corruptEvidence && body?.method === 'tools/call' && body.params.name === 'previsit_evidence_get') {
    body.params.arguments.evidenceId = 'missing-fixture';
    await route.continue({ postData: JSON.stringify(body) });
  } else await route.continue();
});
try {
  await page.goto('http://localhost:8080');
  await page.waitForFunction(() => document.querySelectorAll('select')[1]?.value === 'previsit_report_open');
  const open = async () => { await page.locator('textarea').fill(JSON.stringify({ reportId: 'demo-report', reportVersion: 1 })); await page.getByRole('button', { name: 'Call Tool' }).click(); };
  await open();
  const appFrame = page.frameLocator('iframe').frameLocator('iframe');
  await appFrame.getByRole('heading', { name: '示例智造有限公司（合成）' }).waitFor();
  assert.ok(logs.includes('F24 initialized'));
  await appFrame.getByRole('button', { name: /扩产意向/ }).click();
  await appFrame.locator('#evidence').filter({ hasText: '2026-09-01' }).waitFor();
  await appFrame.getByRole('button', { name: /回款改善/ }).click();
  await appFrame.locator('#evidence').filter({ hasText: '两笔应收款' }).waitFor();
  await appFrame.getByRole('button', { name: /客户集中度/ }).click();
  await appFrame.locator('#evidence').filter({ hasText: '<script>' }).waitFor();
  const frame = await (await appFrame.locator('html').elementHandle()).ownerFrame();
  assert.equal(await frame.evaluate(() => window.externalInstruction), undefined);
  assert.equal(await frame.evaluate(() => { try { return !!top.document.body; } catch { return false; } }), false);
  corruptEvidence = true;
  await appFrame.getByRole('button', { name: /扩产意向/ }).click();
  await appFrame.getByRole('alert').filter({ hasText: 'EVIDENCE_NOT_FOUND' }).waitFor();
  corruptEvidence = false;
  await appFrame.getByRole('button', { name: /扩产意向/ }).click();
  await appFrame.locator('#evidence').filter({ hasText: '2026-09-01' }).waitFor();
  const beforeRepeat = requests.filter(r => r.params?.name === 'previsit_evidence_get').length;
  await appFrame.getByRole('button', { name: /扩产意向/ }).evaluate(b => { b.click(); b.click(); });
  await appFrame.locator('#evidence').filter({ hasText: '2026-09-01' }).waitFor();
  assert.equal(requests.filter(r => r.params?.name === 'previsit_evidence_get').length, beforeRepeat + 1);
  await page.screenshot({ path: new URL('basic-host-desktop.png', evidenceDir).pathname, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.waitForFunction(() => document.querySelector('iframe').getBoundingClientRect().width <= window.innerWidth);
  await frame.waitForFunction(() => window.innerWidth <= 390);
  await page.waitForFunction(() => document.getAnimations().every(a => a.playState !== 'running'));
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  assert.ok(await frame.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth));
  await page.screenshot({ path: new URL('basic-host-mobile-dark.png', evidenceDir).pathname, fullPage: true });
  const wire = (await Promise.all(page.frames().map(f => f.evaluate(() => window.__wire ?? [])))).flat();
  assert.ok(wire.some(m => m.method === 'ui/notifications/tool-result'));
  await page.getByTitle('Close', { exact: true }).click();
  await page.locator('iframe').waitFor({ state: 'detached' });
  assert.ok(logs.includes('F24 teardown-complete'));
  await open();
  await appFrame.getByRole('heading', { name: '示例智造有限公司（合成）' }).waitFor();
  await page.getByTitle('Close', { exact: true }).click();
  await page.locator('iframe').waitFor({ state: 'detached' });
  assert.equal(logs.filter(l => l === 'F24 teardown-complete').length, 2);
  await page.goto('http://localhost:8080');
  await page.waitForFunction(() => document.querySelectorAll('select')[1]?.value === 'previsit_report_open');
  await open();
  await appFrame.getByRole('heading', { name: '示例智造有限公司（合成）' }).waitFor();
  await page.getByTitle('Close', { exact: true }).click();
  await page.locator('iframe').waitFor({ state: 'detached' });
  assert.equal(logs.filter(l => l === 'F24 teardown-complete').length, 3);
  assert.ok(requests.every(r => r.method !== 'tools/call' || ['previsit_report_open', 'previsit_evidence_get'].includes(r.params.name)));
  assert.ok(!pageErrors.length, pageErrors.join('\n'));
  await writeFile(new URL('basic-host-result.json', evidenceDir), JSON.stringify({ passed: true, basicHost: 'ext-apps v2.0.0 / 352f6ced4d80772e92b4e7a311854481a8d65b04', browser: browser.version(), requests, responses, wire, lifecycle: logs.filter(l => l.startsWith('F24')), pageErrors }, null, 2));
  console.log('PASS: discovery/resource/initialize/result/evidence/error/retry/isolation/teardown/remount; no enterprise-query tool exposed or called');
} catch (e) { await writeFile(new URL('basic-host-failure.json', evidenceDir), JSON.stringify({ error: String(e), logs, requests, responses, pageErrors }, null, 2)); throw e; }
finally { await browser.close(); }
